spring.application.name=demo_eureka

server.port=8761
# Démarre le serveur Eureka sur le port 8761.
# Attribue un nom unique au serveur de découverte.
eureka.client.fetch-registry=false
#Empêche le serveur Eureka de récupérer des informations de registre auprès d'un autre serveur Eureka, car il fait office de registre. eureka.client.register-with-eureka=false
