spring.application.name=eureka-server-1

#server.port=8085
server.port=8761

## Le serveur s'enregistre auprès de son pair
#eureka.client.register-with-eureka=true
#
## Le serveur récupère le registre de son pair
#eureka.client.fetch-registry=false
#
## Adresse du serveur Eureka pair
#eureka.client.service-url.defaultZone=http://localhost:8090/eureka/
#
eureka.instance.hostname=localhost
